### ISSUE TITLE
Create expected exception attribute

### ISSUE THREAD

**Issue by lordofthejars** [snowdrop/spring-fallback#1]
Instead of having to write:

```java
public String error(ExecutionContext executionContext) {
        final Throwable t = executionContext.getThrowable();
        if (t instanceof IOException) {
            return "io-fallback";
        }
        else if (t instanceof RuntimeException) {
            return "rt-fallback";
        }
        
        return "default-fallback";
    }
```

Maybe we could do something like:

```java
@Fallback(exception=IOException.class, value = "error1")
@Fallback(exception=RuntimeException.class, value ="error2")
@Fallback(value="deaulterror")
class XXX {
  void errro1(){}
  void error2{}
  void defaulterror(){}
}
```

So we can avoid this if/else structure.

**Comment by geoand** [comment]
This sounds very interesting!

There is only one thing I am concerned about however: how would we handle the case where the exception types are non-overlapping? Would we just assume that we should use the first matching exception handler?

**Comment by lordofthejars** [comment]
I think so, or you can add an order attribute. In case of same number, first found first served.

**Comment by geoand** [comment]
Sounds good to me

I'll start working on it and open a PR when I have something working so you can review if you like :)
